name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Build
        run: dotnet build sources\EncodingChecker.sln --configuration Release

      - name: Test
        run: dotnet test sources\EncodingChecker.sln --configuration Release --no-build
